/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasie;
import aplikasi.db.Mahasiswa;
import aplikasi.db.MahasiswaManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

    
/**
 *
 * @author ThinkPad
 */
public class jendelautama extends javax.swing.JFrame {
    List<Mahasiswa> mahasiswa = new ArrayList<Mahasiswa>();
    int currentRow = 0;
    
    public jendelautama() {
        String lookAndFeel = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try {
            javax.swing.UIManager.setLookAndFeel(lookAndFeel);
        } catch (Exception e) {}
        
        initComponents();
        loadData();
        binData();
        this.setTitle("Data Mahasiswa");
    
        txtNoBP.setEditable(false); 
        txtNama.setEditable(false);
        txtTempatLahir.setEditable(false);
        txtTanggalLahir.setEditable(false);
        txtAlamat.setEditable(false);
        txtTelp.setEditable(false);
        txtAsalSekolah.setEditable(false);
        this.setLocationRelativeTo(this);
    }
 
    private void loadData() {
        MahasiswaManager mhsmgr = new MahasiswaManager();
        mahasiswa = mhsmgr.getMahasiswa();
        mhsmgr.closeConnection();
    }
    private void binData() {
       if (mahasiswa.size()>0) {
           Mahasiswa m = mahasiswa.get(currentRow);
           txtNoBP.setText(m.getNoBP());
           txtNama.setText(m.getNama());
           txtTempatLahir.setText(m.getTempatLahir());
           txtTanggalLahir.setText(m.getTanggalLahir());
           txtAlamat.setText(m.getAlamat());
           txtTelp.setText(m.getTelp());
           txtAsalSekolah.setText(m.getAsalSekolah());
        } else {
           currentRow = 0;
           txtNoBP.setText("");
           txtNama.setText("");
           txtTempatLahir.setText("");
           txtTanggalLahir.setText("");
           txtAlamat.setText("");
           txtTelp.setText("");
           txtAsalSekolah.setText("");
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoBP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtAsalSekolah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NoBP");

        jLabel3.setText("Nama");

        jLabel4.setText("TempatLahir/Tanggal Lahir");

        jLabel5.setText("Alamat");

        jLabel6.setText("Telp");

        jLabel7.setText("AsalSekolah");

        txtNoBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoBPActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalLahirActionPerformed(evt);
            }
        });

        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });

        txtAsalSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsalSekolahActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jLabel8.setText("/");

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnNew.setText("Baru");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoBP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addGap(130, 130, 130)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void txtNoBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoBPActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalLahirActionPerformed

    private void txtAsalSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsalSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsalSekolahActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if(currentRow< mahasiswa.size()-1){
            ++currentRow;
            btnPrev.setEnabled(true);
            if (currentRow == mahasiswa.size() - 1) {
                btnNext.setEnabled(false);
            }
            binData();
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (currentRow > 0) {
            currentRow--;
            btnNext.setEnabled(true);
            if (currentRow == 0) {
                btnPrev.setEnabled(false);
            }
            binData();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if (btnNew.getText().equals("Baru")) {
            txtNoBP.setText("");
            txtNama.setText("");
            txtTempatLahir.setText("");
            txtTanggalLahir.setText("");
            txtAlamat.setText("");
            txtTelp.setText("");
            txtAsalSekolah.setText("");
            
            txtNoBP.setEditable(true);
            txtNama.setEditable(true);
            txtTempatLahir.setEditable(true);
            txtTanggalLahir.setEditable(true);
            txtAlamat.setEditable(true);
            txtTelp.setEditable(true);
            txtAsalSekolah.setEditable(true);
            txtNoBP.requestFocus();
            
            btnNew.setText("Simpan");
            btnDelete.setText("Batal");
            btnEdit.setEnabled(false);
            btnNext.setEnabled(false);
            btnPrev.setEnabled(false);
        } else {
            if (!txtNoBP.getText().equals("") && !txtNama.getText().equals("")) {
                MahasiswaManager mhsmgr = new MahasiswaManager();
                Mahasiswa m = new Mahasiswa();
                m.setNoBP(txtNoBP.getText());
                m.setNama(txtNama.getText());
                m.setTempatLahir(txtTempatLahir.getText());
                m.setTanggalLahir(txtTanggalLahir.getText());
                m.setAlamat(txtAlamat.getText());
                m.setTelp(txtTelp.getText());
                m.setAsalSekolah(txtAsalSekolah.getText());

                if (mhsmgr.Insert(m) > 0) {
                    loadData();       
                    currentRow = mahasiswa.size() - 1;
                    binData();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                
                txtNoBP.setEditable(false);
                txtNama.setEditable(false);
                txtTempatLahir.setEditable(false);
                txtTanggalLahir.setEditable(false);
                txtAlamat.setEditable(false);
                txtTelp.setEditable(false);
                txtAsalSekolah.setEditable(false);
                
                btnNew.setText("Baru");
                btnDelete.setText("Hapus");
                btnEdit.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrev.setEnabled(true);
                mhsmgr.closeConnection();
            } else {
                JOptionPane.showMessageDialog(this, "No BP dan Nama harus diisi",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (btnEdit.getText().equals("Edit")) {
            txtNama.setEditable(true);
            txtTempatLahir.setEditable(true);
            txtTanggalLahir.setEditable(true);
            txtAlamat.setEditable(true);
            txtTelp.setEditable(true);
            txtAsalSekolah.setEditable(true);
            txtNama.requestFocus();
            
            btnEdit.setText("Simpan");
            btnDelete.setText("Batal");
            btnNew.setEnabled(false);
            btnNext.setEnabled(false);
            btnPrev.setEnabled(false);
        } else {
            MahasiswaManager mhsmgr = new MahasiswaManager();
            Mahasiswa m = new Mahasiswa();
            m.setNoBP(txtNoBP.getText());
            m.setNama(txtNama.getText());
            m.setTempatLahir(txtTempatLahir.getText());
            m.setTanggalLahir(txtTanggalLahir.getText());
            m.setAlamat(txtAlamat.getText());
            m.setTelp(txtTelp.getText());
            m.setAsalSekolah(txtAsalSekolah.getText());
            
            if (mhsmgr.Update(m) > 0) {
                loadData();
                binData();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Diupdate",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
            txtNoBP.setEditable(false);
            txtNama.setEditable(false);
            txtTempatLahir.setEditable(false);
            txtTanggalLahir.setEditable(false);
            txtAlamat.setEditable(false);
            txtTelp.setEditable(false);
            txtAsalSekolah.setEditable(false);
            
            btnEdit.setText("Edit");
            btnDelete.setText("Hapus");
            btnNew.setEnabled(true);
            btnNext.setEnabled(true);
            btnPrev.setEnabled(true);
            mhsmgr.closeConnection();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (btnDelete.getText().equals("Hapus")) {
            int dialog = JOptionPane.showConfirmDialog(btnDelete,
                "Apakah Anda Yakin Akan Menghapus Data Ini?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION); 
            MahasiswaManager mhsmgr = new MahasiswaManager();
            Mahasiswa m = mahasiswa.get(currentRow);
            if (dialog == JOptionPane.YES_OPTION) {           
                if (mhsmgr.Delete(m) > 0) {
                    loadData();
                    currentRow = currentRow -1;
                    binData();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                mhsmgr.closeConnection();
            }
        } else if (btnDelete.getText().equals("Batal")) {
            loadData();
            binData();
            
            btnNew.setText("Baru");
            btnEdit.setText("Edit");
            btnDelete.setText("Hapus");
            
            btnEdit.setEnabled(true);
            btnNew.setEnabled(true);
            btnNext.setEnabled(true);
            btnPrev.setEnabled(true);
            
            txtNoBP.setEditable(false);
            txtNama.setEditable(false);
            txtTempatLahir.setEditable(false);
            txtTanggalLahir.setEditable(false);
            txtAlamat.setEditable(false);
            txtTelp.setEditable(false);
            txtAsalSekolah.setEditable(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jendelautama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jendelautama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jendelautama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jendelautama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jendelautama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtAsalSekolah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoBP;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
